default: &default
  adapter: postgis
  encoding: unicode
  pool: 5
  host: localhost
  username: postread
  password: PostRead
  schema_search_path: 'prefeitura'
  port: 5435

development:
  <<: *default
  database: postgiscwb

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: postgiscwb
